(cl:defpackage p_robot_learning_demo-msg
  (:use )
  (:export
   "<URDEMOACTION>"
   "URDEMOACTION"
   "<URDEMOACTIONFEEDBACK>"
   "URDEMOACTIONFEEDBACK"
   "<URDEMOACTIONGOAL>"
   "URDEMOACTIONGOAL"
   "<URDEMOACTIONRESULT>"
   "URDEMOACTIONRESULT"
   "<URDEMOFEEDBACK>"
   "URDEMOFEEDBACK"
   "<URDEMOGOAL>"
   "URDEMOGOAL"
   "<URDEMORESULT>"
   "URDEMORESULT"
  ))

