// Auto-generated. Do not edit!

// (in-package p_robot_learning_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class UrDemoResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_done = null;
      this.rurpos = null;
      this.rf1 = null;
    }
    else {
      if (initObj.hasOwnProperty('action_done')) {
        this.action_done = initObj.action_done
      }
      else {
        this.action_done = 0;
      }
      if (initObj.hasOwnProperty('rurpos')) {
        this.rurpos = initObj.rurpos
      }
      else {
        this.rurpos = [];
      }
      if (initObj.hasOwnProperty('rf1')) {
        this.rf1 = initObj.rf1
      }
      else {
        this.rf1 = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type UrDemoResult
    // Serialize message field [action_done]
    bufferOffset = _serializer.uint32(obj.action_done, buffer, bufferOffset);
    // Serialize message field [rurpos]
    bufferOffset = _arraySerializer.float64(obj.rurpos, buffer, bufferOffset, null);
    // Serialize message field [rf1]
    bufferOffset = _arraySerializer.float64(obj.rf1, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type UrDemoResult
    let len;
    let data = new UrDemoResult(null);
    // Deserialize message field [action_done]
    data.action_done = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [rurpos]
    data.rurpos = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [rf1]
    data.rf1 = _arrayDeserializer.float64(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 8 * object.rurpos.length;
    length += 8 * object.rf1.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'p_robot_learning_demo/UrDemoResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3444c2c0ad381ffdf4a9aeaec324987c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 action_done
    float64[] rurpos
    float64[] rf1
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new UrDemoResult(null);
    if (msg.action_done !== undefined) {
      resolved.action_done = msg.action_done;
    }
    else {
      resolved.action_done = 0
    }

    if (msg.rurpos !== undefined) {
      resolved.rurpos = msg.rurpos;
    }
    else {
      resolved.rurpos = []
    }

    if (msg.rf1 !== undefined) {
      resolved.rf1 = msg.rf1;
    }
    else {
      resolved.rf1 = []
    }

    return resolved;
    }
};

module.exports = UrDemoResult;
