// Auto-generated. Do not edit!

// (in-package p_robot_learning_demo.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class UrDemoFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percent_complete = null;
      this.urposf = null;
      this.f1 = null;
    }
    else {
      if (initObj.hasOwnProperty('percent_complete')) {
        this.percent_complete = initObj.percent_complete
      }
      else {
        this.percent_complete = 0.0;
      }
      if (initObj.hasOwnProperty('urposf')) {
        this.urposf = initObj.urposf
      }
      else {
        this.urposf = [];
      }
      if (initObj.hasOwnProperty('f1')) {
        this.f1 = initObj.f1
      }
      else {
        this.f1 = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type UrDemoFeedback
    // Serialize message field [percent_complete]
    bufferOffset = _serializer.float32(obj.percent_complete, buffer, bufferOffset);
    // Serialize message field [urposf]
    bufferOffset = _arraySerializer.float64(obj.urposf, buffer, bufferOffset, null);
    // Serialize message field [f1]
    bufferOffset = _arraySerializer.float64(obj.f1, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type UrDemoFeedback
    let len;
    let data = new UrDemoFeedback(null);
    // Deserialize message field [percent_complete]
    data.percent_complete = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [urposf]
    data.urposf = _arrayDeserializer.float64(buffer, bufferOffset, null)
    // Deserialize message field [f1]
    data.f1 = _arrayDeserializer.float64(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 8 * object.urposf.length;
    length += 8 * object.f1.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'p_robot_learning_demo/UrDemoFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e39a61614b37725ac045743ec1a3657c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    float32 percent_complete
    float64[] urposf
    float64[] f1
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new UrDemoFeedback(null);
    if (msg.percent_complete !== undefined) {
      resolved.percent_complete = msg.percent_complete;
    }
    else {
      resolved.percent_complete = 0.0
    }

    if (msg.urposf !== undefined) {
      resolved.urposf = msg.urposf;
    }
    else {
      resolved.urposf = []
    }

    if (msg.f1 !== undefined) {
      resolved.f1 = msg.f1;
    }
    else {
      resolved.f1 = []
    }

    return resolved;
    }
};

module.exports = UrDemoFeedback;
